config/routes.rb
Rails.application.routes.draw do
  resources :animals
    root 'pages#home'
    get '/housing', to: 'animals#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]
  require 'httparty'
  include HTTParty
  basic_auth 'username', 'password'
  # GET /animals
  # GET /animals.json
  def index
    @animal = Animal.new
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
    @animal = Animal.find_by_id(params[:id])
    @participantId = @animal.participantId
    @history_hash = fetch_animal(@participantId)
  end

  def fetch_animal participantId
    auth = {:username => 'apikey', :password => ENV['LABKEY_API_KEY']}
    @response = HTTParty.get("http://pczt-win-lbk-a1.primate.ucdavis.edu:8080/labkey/query/CNPRC/selectRows.api?schemaName=study&query.queryName=housing&query.maxRows=40&query.participantid~eq=#{participantId}",:basic_auth => auth)

  end


  # GET /animals/new
  def new
    @animal = Animal.new

    auth = {:username => 'apikey', :password => ENV['LABKEY_API_KEY']}
    @rooms = []
    @response = HTTParty.get("http://pczt-win-lbk-a1.primate.ucdavis.edu:8080/labkey/query/CNPRC/selectRows.api?schemaName=ehr_lookups&query.queryName=rooms&query",:basic_auth => auth)
    @response['rows'].each do |row|
       @rooms.push(row['room'])
    end

  end

  # GET /animals/1/edit
  def edit
    auth = {:username => 'apikey', :password => ENV['LABKEY_API_KEY']}
    @rooms = []
    @response = HTTParty.get("http://pczt-win-lbk-a1.primate.ucdavis.edu:8080/labkey/query/CNPRC/selectRows.api?schemaName=ehr_lookups&query.queryName=rooms&query",:basic_auth => auth)
    @response['rows'].each do |row|
       @rooms.push(row['room'])
    end
  end

  # POST /animals
  # POST /animals.json
  def create
    @search = Animal.new(animal_params)
    auth = {:username => 'apikey', :password => ENV['LABKEY_API_KEY']}
    @participantId = animal_params[:participantId]
    @previous = HTTParty.get("http://pczt-win-lbk-a1.primate.ucdavis.edu:8080/labkey/query/CNPRC/selectRows.api?schemaName=study&query.queryName=housing&query.maxRows=1&query.participantid~eq=#{@participantId}",:basic_auth => auth)
    @result = HTTParty.post("http://pczt-win-lbk-a1.primate.ucdavis.edu:8080/labkey/query/CNPRC/insertRows.api",:basic_auth => auth,
    :body => {"schemaName": "study",
              "queryName": "housing",
              "command": "update",
              "rowsAffected": 1,
              "rows": [
                {"participantId": animal_params[:participantId],
                 "modifiedBy": 1004,
                 # "date": @previous['rows'][0]['enddate'],
                 "date": animal_params[:date],
                 "room": animal_params[:room],
                 "cage": animal_params[:cage],
                 "reloc_seq": @previous['rows'][0]['reloc_seq'].to_i + 1,
                 "Key":SecureRandom.hex.to_s
                 }
              ]
            }.to_json,
    :headers => { 'Content-Type' => 'application/json' } )
    puts @result
    if @search.save
      redirect_to animal_path(@search)
    else
      flash[:error] = @search.errors.full_messages.join(", ")
      redirect_to :back
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    auth = {:username => 'apikey', :password => ENV['LABKEY_API_KEY']}
    @result = HTTParty.post("http://pczt-win-lbk-a1.primate.ucdavis.edu:8080/labkey/query/CNPRC/insertRows.api",:basic_auth => auth,
    :body => {"schemaName": "study",
              "queryName": "housing",
              "command": "update",
              "rowsAffected": 1,
              "rows": [
                {"participantId": animal_params[:participantId],
                 "modifiedBy": 1004,
                 "date": "2014-05-07 00:00:00.000",
                 "enddate": "2014-05-08 00:00:00.000",
                 "room": params['room'],
                 "reloc_seq": animal_params[:reloc_seq],
                 "Key":SecureRandom.hex.to_s
                 }
              ]
            }.to_json,
    :headers => { 'Content-Type' => 'application/json' } )

    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:participantId, :date, :room, :reloc_seq, :objectId,:enddate,:cage)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<br>
  <div class="field">
    <%= form.label :Animal_ID %>
    <%= form.number_field :participantId, id: :animal_participantId, value:params['animal_id'] %>
  </div>

  <div class="field">
    <%= form.label :date_in %>
    <%= form.date_field :date, id: :animal_date %>
  </div>
<br>
  <!-- <div class="field">
    <%= form.label :date_out %>
    <%= form.date_field :enddate, id: :animal_end_date %>
  </div> -->
<br>
  <div class="field">
    <%= form.label :room %>
    <%= form.text_field :room, id: :room %>
<br>
 </div>
  <div class="field">
    <%= form.label :cage %>
    <%= form.text_field :cage, id: :animal_cage %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<span hidden id='room-array'>
  <%=@rooms%>
</span>
<script>
$( document).ready(function(){
  var tags = $('#room-array').text()
  var tags_arr = JSON.parse("[" + tags + "]")
  tags[0].replace('/[','/')
  $( "#room" ).autocomplete({
    source: tags_arr[0]
  });


});
</script>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<h1>Animal Housing Search</h1>
<h4>Search By Id for Animal Housing history</h4>
<br /><% flash.each do |name, msg| %>
<div class="myAlert<% if name==" error" %> alert-danger <% elsif name==" success" %> alert-success <% else %> alert-info <% end %>">
<%= msg %>
</div>
<% end %>
<br><br>
<%= form_for @animal,:url => url_for(:action => 'create', :controller => 'animals'),
    :method => 'post' do |f| %>
<%= f.label :participantId, 'Id' %><br>
<%= f.text_field :participantId, class: "form-control zipcode", placeholder: 'Search here'%>
<%= f.submit "Search", class: 'btn btn-primary btn-md center-block search' %>
<%end%>
<br><br>

app/views/animals/new.html.erb
<h1>New Animal Relocation</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ANimal Housing Report</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-confirmation/1.0.5/bootstrap-confirmation.js"></script>
  </head>
  <body>
  <div class='container'>
    <h3><%=link_to 'Back to Search', '/'%></h3>
    <h4>Searched Id: <%= @animal.participantId%></h4>

    <table style="width:100%">
      <tr>
        <th>Date In</th>
        <!-- <th>Date Out</th> -->
        <th>Cage</th>
        <th>Room</th>
        <th>Relocation #</th>
      </tr>
    <%50.times do |i|%>
      <%if @history_hash['rows'][i]%>
          <tr>
            <td><%= @history_hash['rows'][i]['date']%></td>
            <!-- <td><%= @history_hash['rows'][i]['enddate']%></td> -->
            <td><%= @history_hash['rows'][i]['cage']%></td>
            <td><%= @history_hash['rows'][i]['room']%></td>
            <td><%= @history_hash['rows'][i]['reloc_seq']%></td>
          </tr>
        <%end%>
    <%end%>
    </table>
    <br>
    <h4>
      <%=link_to 'Add New Housing move',new_animal_path(:animal_id=>@animal.participantId)%>
    </h4>
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabkeyApi</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class='container'>
  <h2>LABKEY HTML5 API INTEGRTION</h2>
  <br><br>
  <h3>Housing Relocations</h3>
  <h4><a href='/animals/new'>Data Entry</a>
  <h4><a href='/animals/'>Reports</a>
  <br>
  <br>
  <br>
  <h3>Case Management</h3>
  <h4><a href='#'>Data Entry</a>
  <h4><a href='#'>Reports</a>
</div>